# Generated by Django 5.2.3 on 2025-09-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='default_country',
        ),
    ]
